name: mother
description: The mother of objects.
# version: 1.0.0
# homepage: https://github.com/kikuchy/mother
# author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
